<?php

namespace App\Modules\Academy\Services;

use App\Modules\Squad\DTOs\GeneratedPlayerData;
use App\Models\AcademyPlayer;
use App\Models\Game;
use App\Models\GamePlayer;
use App\Modules\Player\PlayerAge;
use Illuminate\Support\Collection;
use Illuminate\Support\Str;
use App\Modules\Squad\Services\PlayerGeneratorService;
use App\Modules\Squad\Services\SquadNumberService;

class YouthAcademyService
{
    /**
     * Tier configuration: [min_arrivals, max_arrivals]
     */
    private const TIER_CONFIG = [
        0 => [0, 0],
        1 => [2, 3],
        2 => [3, 5],
        3 => [4, 6],
        4 => [4, 6],
    ];

    /**
     * Base average ability for prospects generated by each academy tier.
     * Higher tiers produce better players on average.
     */
    private const ACADEMY_BASE_QUALITY = [
        0 => 0,
        1 => 45,   // Basic: developing players
        2 => 52,   // Good: slightly above developing
        3 => 62,   // Elite: average-to-good
        4 => 70,   // World-Class: good, ready to contribute
    ];

    /**
     * Small adjustment to the ability mean based on first team's median tier.
     * Keeps academy output contextually anchored to club strength.
     */
    private const TEAM_CONTEXT_BONUS = [
        1 => -3,
        2 => -1,
        3 => 0,
        4 => 2,
        5 => 4,
    ];

    /**
     * Standard deviation for the ability normal distribution.
     * Uniform across all tiers — only the mean differentiates them.
     */
    private const ABILITY_STD_DEV = 6;

    /**
     * Average potential upside (points above current ability) per academy tier.
     */
    private const POTENTIAL_UPSIDE_MEAN = [
        0 => 0,
        1 => 15,
        2 => 15,
        3 => 10,
        4 => 10,
    ];

    /**
     * Standard deviation for potential upside sampling.
     */
    private const POTENTIAL_UPSIDE_STD_DEV = 5;

    /**
     * Absolute minimum potential guaranteed by academy tier, regardless of team level.
     */
    private const POTENTIAL_FLOOR = [
        0 => 0,
        1 => 45,
        2 => 50,
        3 => 55,
        4 => 60,
    ];

    private const ESTIMATED_MATCHDAYS = 38;

    /**
     * Season growth rates for development.
     */
    private const GROWTH_RATE_ACADEMY = 0.45;
    private const GROWTH_RATE_LOAN = 0.50;

    /**
     * Position groups with weights for random selection.
     * First a group is chosen by weight, then a specific position within it.
     */
    private const POSITION_GROUPS = [
        ['weight' => 9,  'positions' => ['Goalkeeper']],
        ['weight' => 33, 'positions' => ['Centre-Back', 'Left-Back', 'Right-Back']],
        ['weight' => 29, 'positions' => ['Defensive Midfield', 'Central Midfield', 'Attacking Midfield']],
        ['weight' => 29, 'positions' => ['Left Winger', 'Right Winger', 'Centre-Forward']],
    ];

    public function __construct(
        private readonly PlayerGeneratorService $playerGenerator,
        private readonly SquadNumberService $squadNumberService,
    ) {}

    /**
     * Generate a batch of new academy prospects at season start.
     *
     * @return Collection<int, AcademyPlayer>
     */
    public function generateSeasonBatch(Game $game): Collection
    {
        $tier = $game->currentInvestment->youth_academy_tier ?? 0;

        if ($tier === 0) {
            return collect();
        }

        $config = self::TIER_CONFIG[$tier];
        [$minArrivals, $maxArrivals] = $config;

        $count = rand($minArrivals, $maxArrivals);
        $teamMedianTier = $this->getTeamMedianTier($game);
        $excludedNames = $this->getExistingPlayerNames($game);

        $prospects = collect();

        for ($i = 0; $i < $count; $i++) {
            $prospect = $this->createAcademyProspect($game, $tier, $teamMedianTier, $excludedNames);
            $excludedNames[] = $prospect->name;
            $prospects->push($prospect);
        }

        return $prospects;
    }

    /**
     * Develop all academy players' abilities for one matchday.
     * Growth is applied each matchday as a small increment toward potential.
     * Only non-loaned players develop (loaned develop at season end).
     */
    public function developPlayers(Game $game): void
    {
        $players = AcademyPlayer::where('game_id', $game->id)
            ->where('team_id', $game->team_id)
            ->where('is_on_loan', false)
            ->get();

        if ($players->isEmpty()) {
            return;
        }

        // Compute growth in memory, batch update changed players in a single query
        $updates = []; // [id => [technical_ability => N, physical_ability => N]]
        foreach ($players as $player) {
            $computed = $this->computeGrowth($player, self::GROWTH_RATE_ACADEMY);
            if ($computed) {
                $updates[$player->id] = $computed;
            }
        }

        if (! empty($updates)) {
            $this->bulkUpdateAbilities($updates);
        }
    }

    /**
     * Compute one matchday of growth for a player (pure calculation, no DB).
     *
     * @return array{technical_ability: int, physical_ability: int}|null Null if no change
     */
    private function computeGrowth(AcademyPlayer $player, float $seasonRate): ?array
    {
        $growthPerMatchday = fn (int $current, int $potential) => max(0, ($potential - $current) * $seasonRate / self::ESTIMATED_MATCHDAYS);

        $techGrowth = $growthPerMatchday($player->technical_ability, $player->potential);
        $physGrowth = $growthPerMatchday($player->physical_ability, $player->potential);

        $newTech = min($player->potential, $player->technical_ability + $techGrowth);
        $newPhys = min($player->potential, $player->physical_ability + $physGrowth);

        $techInt = (int) round($newTech);
        $physInt = (int) round($newPhys);

        if ($techInt === $player->technical_ability && $physInt === $player->physical_ability) {
            return null;
        }

        return ['technical_ability' => $techInt, 'physical_ability' => $physInt];
    }

    /**
     * Bulk update abilities using CASE WHEN (1 query instead of N).
     *
     * @param  array<string, array{technical_ability: int, physical_ability: int}>  $updates
     */
    private function bulkUpdateAbilities(array $updates): void
    {
        $ids = array_keys($updates);
        $idList = "'" . implode("','", $ids) . "'";

        $techCases = [];
        $physCases = [];
        foreach ($updates as $id => $values) {
            $techCases[] = "WHEN id = '{$id}' THEN {$values['technical_ability']}";
            $physCases[] = "WHEN id = '{$id}' THEN {$values['physical_ability']}";
        }

        \Illuminate\Support\Facades\DB::statement("
            UPDATE academy_players
            SET technical_ability = CASE " . implode(' ', $techCases) . " ELSE technical_ability END,
                physical_ability = CASE " . implode(' ', $physCases) . " ELSE physical_ability END
            WHERE id IN ({$idList})
        ");
    }

    /**
     * Apply a full season of off-screen development to loaned players.
     * Called at season end when loans return.
     */
    public function developLoanedPlayers(Game $game): void
    {
        $loanedPlayers = AcademyPlayer::where('game_id', $game->id)
            ->where('team_id', $game->team_id)
            ->where('is_on_loan', true)
            ->get();

        foreach ($loanedPlayers as $player) {
            // Apply full season growth at loan rate
            $techGrowth = ($player->potential - $player->technical_ability) * self::GROWTH_RATE_LOAN;
            $physGrowth = ($player->potential - $player->physical_ability) * self::GROWTH_RATE_LOAN;

            $player->update([
                'technical_ability' => min($player->potential, (int) round($player->technical_ability + $techGrowth)),
                'physical_ability' => min($player->potential, (int) round($player->physical_ability + $physGrowth)),
            ]);
        }
    }

    /**
     * Return all loaned players to the academy at season end.
     *
     * @return Collection<int, AcademyPlayer> The returned players
     */
    public function returnLoans(Game $game): Collection
    {
        $loanedPlayers = AcademyPlayer::where('game_id', $game->id)
            ->where('team_id', $game->team_id)
            ->where('is_on_loan', true)
            ->get();

        foreach ($loanedPlayers as $player) {
            $player->update(['is_on_loan' => false]);
        }

        return $loanedPlayers;
    }

    /**
     * Mark a player as loaned out.
     */
    public function loanPlayer(AcademyPlayer $player): void
    {
        $player->update(['is_on_loan' => true]);
    }

    /**
     * Dismiss a player from the academy (permanently removed).
     */
    public function dismissPlayer(AcademyPlayer $player): void
    {
        $player->delete();
    }

    /**
     * Promote an academy player to the first team.
     * Creates Player + GamePlayer records and deletes the AcademyPlayer.
     */
    public function promoteToFirstTeam(AcademyPlayer $academy, Game $game): GamePlayer
    {
        $gamePlayer = $this->playerGenerator->create($game, new GeneratedPlayerData(
            teamId: $academy->team_id,
            position: $academy->position,
            technical: $academy->technical_ability,
            physical: $academy->physical_ability,
            dateOfBirth: $academy->date_of_birth,
            contractYears: 2,
            name: $academy->name,
            nationality: $academy->nationality,
            potential: $academy->potential,
            potentialLow: $academy->potential_low,
            potentialHigh: $academy->potential_high,
            fitnessMin: 85,
            fitnessMax: 100,
            moraleMin: 70,
            moraleMax: 90,
        ));

        $gamePlayer->update([
            'number' => $this->squadNumberService->assignNumberForNewPlayer($game, $gamePlayer),
        ]);

        $academy->delete();

        return $gamePlayer;
    }

    /**
     * Auto-promote all academy players who have reached ACADEMY_END age.
     *
     * @return Collection<int, GamePlayer> The promoted players
     */
    public function promoteOveragePlayers(Game $game): Collection
    {
        if (! $game->current_date) {
            return collect();
        }

        $cutoff = PlayerAge::dateOfBirthCutoff(PlayerAge::ACADEMY_END, $game->current_date);

        $overagePlayers = AcademyPlayer::where('game_id', $game->id)
            ->where('team_id', $game->team_id)
            ->where('date_of_birth', '<=', $cutoff)
            ->get();

        return $overagePlayers->map(fn (AcademyPlayer $academy) => $this->promoteToFirstTeam($academy, $game));
    }

    /**
     * Promote the N highest-potential non-loaned academy players to the first team.
     *
     * @return Collection<int, GamePlayer> The promoted players
     */
    public function promoteBestPlayers(Game $game, int $count): Collection
    {
        if ($count <= 0) {
            return collect();
        }

        $candidates = AcademyPlayer::where('game_id', $game->id)
            ->where('team_id', $game->team_id)
            ->where('is_on_loan', false)
            ->orderByDesc('potential')
            ->limit($count)
            ->get();

        return $candidates->map(fn (AcademyPlayer $academy) => $this->promoteToFirstTeam($academy, $game));
    }

    /**
     * Get the expected new arrivals range for a tier.
     *
     * @return array{min: int, max: int}
     */
    public static function getArrivalsRange(int $tier): array
    {
        $config = self::TIER_CONFIG[$tier] ?? self::TIER_CONFIG[0];

        return ['min' => $config[0], 'max' => $config[1]];
    }

    public static function getTierDescription(int $tier): string
    {
        return __('squad.academy_tier_'.(match ($tier) {
            0, 1, 2, 3, 4 => $tier,
            default => 'unknown',
        }));
    }

    public static function getProspectInfo(int $tier): array
    {
        $config = self::TIER_CONFIG[$tier] ?? self::TIER_CONFIG[0];

        return [
            'min_prospects' => $config[0],
            'max_prospects' => $config[1],
        ];
    }

    /**
     * Teams whose academy only produces domestic players (cantera philosophy).
     * Maps team name → exact nationality filter (overrides weighted selection).
     */
    private const CANTERA_TEAMS = [
        'Athletic Bilbao' => 'Spain',
    ];

    /**
     * Create an academy prospect record.
     * Quality follows a normal distribution centered on the academy tier's base quality,
     * adjusted by team context. This produces realistic clustering around the mean
     * with occasional gems and busts in the tails.
     */
    private function createAcademyProspect(
        Game $game,
        int $academyTier,
        int $teamMedianTier,
        array $excludedNames,
    ): AcademyPlayer {
        $position = $this->selectPosition();

        // Ability mean = academy base quality + team context bonus
        $abilityMean = self::ACADEMY_BASE_QUALITY[$academyTier] + self::TEAM_CONTEXT_BONUS[$teamMedianTier];

        $technical = $this->clampAbility($this->gaussianRandom($abilityMean, self::ABILITY_STD_DEV));
        $physical = $this->clampAbility($this->gaussianRandom($abilityMean, self::ABILITY_STD_DEV));

        // Potential = best current ability + normally distributed upside
        $currentBest = max($technical, $physical);
        $upsideMean = self::POTENTIAL_UPSIDE_MEAN[$academyTier];
        $upside = max(0, (int) round($this->gaussianRandom($upsideMean, self::POTENTIAL_UPSIDE_STD_DEV)));
        $potential = $currentBest + $upside;

        // Apply floor guarantee and ceiling
        $potential = max($potential, self::POTENTIAL_FLOOR[$academyTier]);
        $potential = min(95, max($potential, $currentBest));

        $potentialVariance = rand(3, 8);
        $potentialLow = max($potential - $potentialVariance, $currentBest);
        $potentialHigh = min($potential + $potentialVariance, 99);

        $age = rand(17, 19);
        $dateOfBirth = $game->current_date->copy()->subYears($age)->subDays(rand(0, 364));

        $teamName = $game->team->name;
        $nationalityFilter = self::CANTERA_TEAMS[$teamName] ?? null;
        $teamCountry = $nationalityFilter ? null : $game->team->country;
        $identity = $this->playerGenerator->pickRandomIdentity($nationalityFilter, $teamCountry, $excludedNames);

        return AcademyPlayer::create([
            'id' => Str::uuid()->toString(),
            'game_id' => $game->id,
            'team_id' => $game->team_id,
            'name' => $identity['name'],
            'nationality' => $identity['nationality'],
            'date_of_birth' => $dateOfBirth,
            'position' => $position,
            'technical_ability' => $technical,
            'physical_ability' => $physical,
            'potential' => $potential,
            'potential_low' => $potentialLow,
            'potential_high' => $potentialHigh,
            'appeared_at' => $game->current_date,
            'is_on_loan' => false,
            'joined_season' => (int) $game->season,
            'initial_technical' => $technical,
            'initial_physical' => $physical,
        ]);
    }

    /**
     * Generate a normally distributed random value using the Box-Muller transform.
     */
    private function gaussianRandom(float $mean, float $stdDev): float
    {
        $u1 = mt_rand(1, PHP_INT_MAX) / PHP_INT_MAX;
        $u2 = mt_rand(1, PHP_INT_MAX) / PHP_INT_MAX;

        $z = sqrt(-2.0 * log($u1)) * cos(2.0 * M_PI * $u2);

        return $mean + $stdDev * $z;
    }

    /**
     * Clamp a sampled ability value to the valid academy prospect range.
     */
    private function clampAbility(float $value): int
    {
        return max(50, min(90, (int) round($value)));
    }

    /**
     * Get the median PlayerTier of the first team's squad.
     */
    private function getTeamMedianTier(Game $game): int
    {
        $tiers = GamePlayer::where('game_id', $game->id)
            ->where('team_id', $game->team_id)
            ->pluck('tier')
            ->sort()
            ->values();

        if ($tiers->isEmpty()) {
            return 2; // fallback for empty squads
        }

        $midIndex = intdiv($tiers->count(), 2);

        return $tiers[$midIndex];
    }

    /**
     * Get names of existing first-team and academy players (to prevent duplicate names).
     *
     * @return string[]
     */
    private function getExistingPlayerNames(Game $game): array
    {
        $firstTeamNames = GamePlayer::where('game_id', $game->id)
            ->where('team_id', $game->team_id)
            ->join('players', 'game_players.player_id', '=', 'players.id')
            ->pluck('players.name')
            ->toArray();

        $academyNames = AcademyPlayer::where('game_id', $game->id)
            ->where('team_id', $game->team_id)
            ->pluck('name')
            ->toArray();

        return array_merge($firstTeamNames, $academyNames);
    }

    private function selectPosition(): string
    {
        $random = rand(1, 100);

        foreach (self::POSITION_GROUPS as $group) {
            $random -= $group['weight'];
            if ($random <= 0) {
                return $group['positions'][array_rand($group['positions'])];
            }
        }

        return 'Central Midfield';
    }
}
